import Foundation

@main
struct RealtimeVoiceClientCheck {
    static func main() throws {
        let sourceURL = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
            .appendingPathComponent("apps/ios/RealtimeSessionClient.swift")
        let source = try String(contentsOf: sourceURL, encoding: .utf8)

        precondition(!source.contains("SFSpeechRecognizer"), "Realtime audio must not use on-device speech recognition.")
        precondition(!source.contains("AVSpeechSynthesizer"), "Realtime audio must not fall back to native text-to-speech.")
        precondition(source.contains("input_audio_buffer.append"), "Microphone PCM must stream directly to Realtime.")
        precondition(source.contains("input_audio_buffer.commit"), "Releasing Talk must commit the captured Realtime audio turn.")
        precondition(source.contains("isListening = true\n        status = \"Listening now."), "Talk must visibly enter the listening state before microphone startup completes.")
        precondition(source.contains("isConnecting"), "Connection state must be distinct from a ready voice connection.")
        precondition(source.contains("audioEngine.stop()"), "Disconnect must stop active Realtime audio capture and playback.")
        precondition(source.contains("webSocket = nil"), "Disconnect must release the Realtime WebSocket.")
        precondition(source.contains("response.output_audio.delta"), "Realtime output PCM must be played directly.")
        precondition(source.contains("response.cancel"), "Talk must cancel active guide audio before capturing an interruption.")
        precondition(!source.contains("AVAudioUnitTimePitch"), "Realtime playback must use the original direct PCM path without a time-pitch effect.")
        precondition(source.contains("audioEngine.connect(playerNode, to: audioEngine.mainMixerNode, format: realtimeAudioFormat)"), "Realtime output must connect directly to the mixer at its wire PCM format.")
        precondition(source.contains("drainTranscript(for:"), "Transcript text must be paced with scheduled audio playback.")
        precondition(source.contains("initialCapabilityTool"), "The first supported voice turn must activate the selected typed demo capability through its native tool.")
        precondition(source.contains("activate_adjacent_room_expansion_assessment"), "The client must activate the typed adjacent-room expansion demo path.")
        precondition(source.contains("candidate_opening"), "The client must accept a user-selected candidate divider-wall opening.")
        precondition(source.contains("roomExpansion"), "The client must retain the conceptual room-expansion result for Results.")
        precondition(source.contains("pendingEvidencePhotoRequest"), "The native camera transition must wait until the guide's spoken response completes.")
        precondition(source.contains("completionCallbackType: .dataPlayedBack"), "Camera and transcript state must advance from completed audio playback, not receipt of an audio packet.")
        precondition(source.contains("response.output_audio.done"), "The client must wait for Realtime to finish streaming output audio before completing the turn.")
        precondition(source.contains("responseAudioDidFinish"), "The client must distinguish audio-stream completion from response completion before revealing transcript text or a camera request.")
        precondition(source.contains("finishResponseAfterPlayback"), "A completed Realtime response must wait for all scheduled guide audio before activating native requests.")
        precondition(source.contains("scheduledPlaybackBufferCount"), "The client must track every scheduled guide audio buffer before treating a response as complete.")
        precondition(source.contains("Already waiting for the user to place"), "Duplicate placement calls must not create a second active placement request.")
        precondition(source.contains("hasPlacedElectricalPanel"), "The native client must reject an EVSE placement until the electrical panel has been placed.")
        precondition(source.contains("requiringTool: \"request_evidence_photo\""), "The first panel-photo request must be forced immediately after EV assessment activation.")
        precondition(source.contains("advanceLevel2EVWorkflow"), "Persisted EV workflow transitions must be advanced through the deterministic assessment gate.")
        precondition(source.contains("case \"place_panel_location\":"), "The deterministic gate must force the panel model-placement transition.")
        precondition(source.contains("case \"place_evse_location\":"), "The deterministic gate must force the EVSE model-placement transition.")
        precondition(source.contains("case \"record_route_waypoints\":"), "The deterministic gate must force the route model-placement transition.")
        precondition(source.contains("Task { await advanceLevel2EVWorkflow() }\n        status = \"Route waypoints were recorded"), "Completing a route must use the deterministic gate before requesting another guide response.")
        precondition(source.contains("routeWaypointCount"), "The native route flow must retain a live waypoint count until the user finishes it.")
        precondition(source.contains("call request_spatial_placement for electrical_panel in this same response"), "Panel tap instructions must require their tool call in the same response.")
        precondition(source.contains("call request_spatial_placement for evse in this same response"), "EVSE tap instructions must require their tool call in the same response.")
        precondition(source.contains("transcriptCharactersPerSecond = 16.0"), "Transcript pacing must track normal spoken output closely.")
        precondition(source.contains("highlight_spatial_reference"), "The client must render the guide's typed model-reference highlights.")
        precondition(source.contains("assessmentContext: RealtimeAssessmentContext"), "Realtime minting must include typed assessment context.")
        precondition(source.contains("Analyze this requested evidence photo now."), "Requested evidence photos must prompt an immediate visual response.")
        precondition(source.contains("Only the electrical-panel photo is supported in this EV assessment."), "The native EV flow must reject charger-location and route photos in favor of model taps.")
        precondition(source.contains(".defaultToSpeaker"), "Realtime playback must prefer the device loudspeaker for every guide response.")
        precondition(source.contains("overrideOutputAudioPort(.speaker)"), "Realtime playback must explicitly retain loudspeaker output when iOS changes audio routes.")
        precondition(!source.contains("mode: .voiceChat"), "Realtime playback must not use phone-call audio routing.")
        precondition(source.contains("\"type\": \"realtime\""), "Realtime session updates must declare the required session type.")
        precondition(source.contains("\"output\": [\n                            \"format\": [\"type\": \"audio/pcm\", \"rate\": 24_000]"), "PCM output format must declare its required sample rate.")
        precondition(
            source.contains("webSocket.send(.string(String(decoding: data, as: UTF8.self)))"),
            "Realtime JSON events must use text WebSocket frames."
        )
        print("Realtime voice turn delivery check passed.")
    }
}
